services:
    sg_datatables.serializer.method:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer

    sg_datatables.serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder

    sg_datatables.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - ['@sg_datatables.serializer.method']
            - ['@sg_datatables.serializer.encoder.json']

    sg_datatables.twig.extension:
        class: Sg\DatatablesBundle\Twig\DatatableTwigExtension
        public: false
        tags:
            - { name: twig.extension }

    sg_datatables.datatable.abstract:
        class: Sg\DatatablesBundle\Datatable\AbstractDatatable
        abstract: true
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@translator.default'
            - '@router'
            - '@doctrine.orm.entity_manager'
